# Generated by Django 5.2.6 on 2025-09-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.PositiveSmallIntegerField(choices=[(1, 'TOYOTA'), (2, 'FORD'), (3, 'CHEVROLET'), (4, 'HONDA'), (5, 'NISSAN'), (6, 'VOLKSWAGEN'), (7, 'HYUNDAI'), (8, 'KIA'), (9, 'RENAULT'), (10, 'PEUGEOT')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('combustivel', models.PositiveSmallIntegerField(choices=[(1, 'GASOLINA'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'ELÉTRICO'), (5, 'HÍBRIDO')])),
                ('cor', models.PositiveSmallIntegerField(choices=[(1, 'VERMELHO'), (2, 'AZUL'), (3, 'PRETO'), (4, 'BRANCO'), (5, 'PRATA'), (6, 'CINZA'), (7, 'VERDE'), (8, 'AMARELO'), (9, 'LARANJA'), (10, 'ROXO')])),
            ],
        ),
    ]
